### PR TITLE
Add float arrays

### PR DESCRIPTION
**Pull request by lganzzzo**
Support multidimensional array deserialization

### CODE REVIEW

**Review by dsmyth — APPROVED** [review]
LGTM

**Comment by dsmyth** [comment]
@lganzzzo Any thoughts on the serialization side? What I have is pretty basic, but it meets my immediate needs.
RE: JSONB support -- I have a workaround by casting to/from TEXT in my queries, so I'm OK there.

**Comment by lganzzzo** [comment]
Hey @dsmyth , 

> Any thoughts on the serialization side? What I have is pretty basic, but it meets my immediate needs.

Yes, I plan to add the serialization part too.
In any case, arrays feature will be merged to master only when it's complete (deserialization + serialization)

I plan to work on it during the next couple of days, so hopefully, it'll be finished by the beginning of the next week

**Comment by lganzzzo** [comment]
> RE: JSONB support -- I have a workaround by casting to/from TEXT in my queries, so I'm OK there

Do you mean the Postgres cast - on the DB engine side?

**Comment by dsmyth** [comment]
Yes, on the DB side. My results field is a String in the analytics DTO.

In my select queries, I do this:
          "CAST(results AS TEXT) "

In my insert and update queries, I do this:
          "CAST(:analytics.results AS JSONB), "

Seems to work fine.

**Pull request merged**
